// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VkBot.Information.User;

namespace VkBot.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190202082522_GeoPos")]
    partial class GeoPos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("VkBot.Information.User.Models.GeoPosition", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commentary");

                    b.Property<string>("Place");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("UserId");

                    b.ToTable("GeoPositions");
                });

            modelBuilder.Entity("VkBot.Information.User.Models.Nickname", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nick");

                    b.HasKey("UserId");

                    b.ToTable("Nicknames");
                });
#pragma warning restore 612, 618
        }
    }
}
